# Generated by Django 5.2.6 on 2025-09-27 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.user')),
                ('course', models.CharField(max_length=50)),
                ('year', models.IntegerField(default=1)),
                ('department', models.CharField(max_length=50)),
            ],
            bases=('account.user',),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('S', 'Student'), ('T', 'Teacher')], default='S', max_length=1),
        ),
    ]
