# Generated by Django 5.2.6 on 2025-09-27 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_student_alter_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.user')),
                ('specialization', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=1)),
            ],
            bases=('account.user',),
        ),
    ]
