# Generated by Django 5.2.6 on 2025-09-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventid', models.AutoField(primary_key=True, serialize=False)),
                ('eventtitle', models.CharField(max_length=100)),
                ('dateofevent', models.DateField()),
                ('maxparticipants', models.IntegerField(default=1)),
                ('teacher', models.ManyToManyField(to='account.teacher')),
            ],
        ),
    ]
