# Generated by Django 5.2.6 on 2025-09-27 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createevent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomid', models.AutoField(primary_key=True, serialize=False)),
                ('roomname', models.CharField(max_length=50)),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createevent.event')),
            ],
        ),
    ]
