# Generated by Django 5.2.6 on 2025-09-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createevent', '0003_attendevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendevent',
            old_name='username',
            new_name='student',
        ),
        migrations.AddField(
            model_name='event',
            name='attend',
            field=models.ManyToManyField(through='createevent.AttendEvent', to='createevent.event'),
        ),
    ]
